/* Bounded, non-persistent multimodal feasibility preview. */
(() => {
  const API_BASE_URL='https://uk-road-tracker-api.onrender.com';
  const TILES={
    gravesend:{label:'Gravesend, Kent',url:'gravesend-network-v1.json.gz',bounds:{south:51.425,west:.350,north:51.445,east:.385}},
    'central-london':{label:'Central London',url:'central-london-network-v1.json.gz',bounds:{south:51.495,west:-.155,north:51.515,east:-.105}}
  };
  const CELL=20,RADIUS=12,LIMIT=20;
  const $=id=>document.getElementById(id);
  const card=$('experimentalCoverageCard'),input=$('coverageTimelineFile'),fileStatus=$('coverageFileStatus');
  const matchButton=$('coverageMatchActivities'),clearButton=$('coverageClearActivities'),status=$('coverageProofStatus');
  const tileSelect=$('coverageTile');
  let activeTile='gravesend',network,segments=[],grid=new Map(),savedDriving=[],onFoot=[],allOnFootActivities=[],map,control;

  input.addEventListener('change',readTimeline);
  matchButton.addEventListener('click',matchActivities);
  clearButton.addEventListener('click',resetTileResults);
  tileSelect.addEventListener('change',selectTile);
  window.addEventListener('roadprints:archivechange',refreshDriving);
  initialise();

  async function initialise(){
    try{
      const [loaded,driving]=await Promise.all([loadNetwork(activeTile),loadDriving()]);
      network=loaded;savedDriving=driving;indexNetwork();initMap();
      if(savedDriving.length) card.classList.remove('hidden');
      render();
    }catch(error){status.className='error map-status';status.textContent=`Coverage preview could not load: ${error.message||error}`;}
  }
  async function loadNetwork(tileId){
    const response=await fetch(TILES[tileId].url,{cache:'no-store'});
    if(!response.ok) throw new Error(`reference network HTTP ${response.status}`);
    if(!globalThis.DecompressionStream) throw new Error('This browser cannot open the compressed reference network.');
    return new Response(response.body.pipeThrough(new DecompressionStream('gzip'))).json();
  }
  function loadDriving(){return new Promise(resolve=>{
    if(!globalThis.indexedDB) return resolve([]);
    const request=indexedDB.open('roadprints-map-archive');
    request.onerror=()=>resolve([]);request.onupgradeneeded=()=>request.transaction?.abort();
    request.onsuccess=()=>{const db=request.result;if(!db.objectStoreNames.contains('journeys')){db.close();return resolve([]);}
      const get=db.transaction('journeys','readonly').objectStore('journeys').getAll();
      get.onerror=()=>{db.close();resolve([])};get.onsuccess=()=>{const value=(get.result||[]).map(x=>x?.matchedGeoJson).filter(Boolean);db.close();resolve(value);};
    };
  });}
  async function refreshDriving(){savedDriving=await loadDriving();if(savedDriving.length)card.classList.remove('hidden');render();}
  function bounds(){return TILES[activeTile].bounds;}
  function project([lng,lat]){const b=bounds(),centre=(b.south+b.north)/2;return{x:(lng-b.west)*111320*Math.cos(centre*Math.PI/180),y:(lat-b.south)*110540};}
  function key(x,y){return `${Math.floor(x/CELL)}:${Math.floor(y/CELL)}`;}
  function indexNetwork(){segments=network.features.map(feature=>{const [start,end]=feature.geometry.coordinates,a=project(start),b=project(end),item={feature,a,b,modes:new Set(feature.properties.modes||[])};
    for(let x=Math.floor((Math.min(a.x,b.x)-RADIUS)/CELL);x<=Math.floor((Math.max(a.x,b.x)+RADIUS)/CELL);x++)for(let y=Math.floor((Math.min(a.y,b.y)-RADIUS)/CELL);y<=Math.floor((Math.max(a.y,b.y)+RADIUS)/CELL);y++){const k=`${x}:${y}`;if(!grid.has(k))grid.set(k,[]);grid.get(k).push(item);}return item;});}
  function initMap(){if(!map){map=L.map('coverageMap',{preferCanvas:true});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);}const b=bounds();map.fitBounds([[b.south,b.west],[b.north,b.east]],{padding:[8,8]});setTimeout(()=>map.invalidateSize(true),50);}
  async function readTimeline(){const file=input.files?.[0];if(!file)return;fileStatus.className='muted map-status';fileStatus.textContent=`Reading ${file.name}…`;
    try{allOnFootActivities=extractActivities(JSON.parse(await file.text()));await prepareTileActivities();renderInventory(allOnFootActivities);card.classList.remove('hidden');
      fileStatus.textContent=onFoot.length?`${allOnFootActivities.length.toLocaleString()} usable walking/running activities inventoried; ${onFoot.length} enter ${TILES[activeTile].label}.`:`${allOnFootActivities.length.toLocaleString()} usable walking/running activities inventoried, but none enter ${TILES[activeTile].label}.`;render();updateQueueButton();
    }catch(error){fileStatus.className='error map-status';fileStatus.textContent=`Could not read this file: ${error.message||error}`;}}
  async function selectTile(){activeTile=tileSelect.value;network=null;segments=[];grid=new Map();status.className='muted map-status';status.textContent=`Loading ${TILES[activeTile].label} reference network…`;try{network=await loadNetwork(activeTile);indexNetwork();initMap();await prepareTileActivities();$('coverageTitle').textContent=`${TILES[activeTile].label}: driven + on foot`;if(allOnFootActivities.length)renderInventory(allOnFootActivities);render();updateQueueButton();}catch(error){status.className='error map-status';status.textContent=`Could not load ${TILES[activeTile].label}: ${error.message||error}`;}}
  async function prepareTileActivities(){const stored=window.RoadprintsCoverageStore?await window.RoadprintsCoverageStore.getActivities():[];const previous=new Map(stored.map(a=>[a.id,a]));onFoot=allOnFootActivities.filter(a=>a.points.some(inBounds)).map(a=>{const old=previous.get(a.id);return old?{...a,geojson:old.matchedGeoJson||null,error:old.matchError||null,state:old.state}:a;});classifyRouteRepeats(onFoot);renderLedger();}
  async function resetTileResults(){if(window.RoadprintsCoverageStore)await window.RoadprintsCoverageStore.clearActivitiesForTile(activeTile);onFoot.forEach(a=>{delete a.geojson;delete a.error;a.state='queued';});fileStatus.className='muted map-status';fileStatus.textContent=`Experimental ${TILES[activeTile].label} results reset on this device.`;render();updateQueueButton();}
  function updateQueueButton(){const pending=onFoot.filter(a=>!a.repeatOf&&!a.geojson&&!a.error).length;matchButton.disabled=!pending;clearButton.disabled=!onFoot.length;matchButton.textContent=pending?`Match next ${Math.min(LIMIT,pending)} of ${pending}`:`All ${TILES[activeTile].label} routes attempted`;}
  async function saveActivity(activity){if(!window.RoadprintsCoverageStore)return;await window.RoadprintsCoverageStore.putActivity({id:activity.id,sourceId:'timeline-import',mode:activity.mode,state:activity.state||'queued',startedAt:activity.start,endedAt:activity.end,tileIds:[activeTile],points:activity.points,matcherVersion:'foot-osrm-v1',matchedGeoJson:activity.geojson||null,matchError:activity.error||null,repeatOf:activity.repeatOf||null,googleDistanceM:activity.googleDistanceM});}
  async function matchActivities(){const pending=onFoot.filter(a=>!a.repeatOf&&!a.geojson&&!a.error).slice(0,LIMIT);if(!pending.length){updateQueueButton();return;}matchButton.disabled=true;clearButton.disabled=true;let complete=0,succeeded=0,failed=0;
    try{for(const activity of pending){complete++;matchButton.textContent=`Matching ${complete} of ${pending.length}…`;fileStatus.className='muted map-status';fileStatus.textContent=`Matching ${TILES[activeTile].label} route ${complete} of ${pending.length}. Keep this page open; each activity may take a few seconds.`;status.className='muted map-status';status.textContent=`Waiting for the pedestrian matcher (${complete}/${pending.length})…`;activity.state='matching';const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),60000);let response,data;try{response=await fetch(`${API_BASE_URL}/match-walking`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({points:activity.points}),signal:controller.signal});data=await response.json().catch(()=>({}));}finally{clearTimeout(timeout);}if(response.ok&&data.geojson?.features?.length){activity.geojson=data.geojson;activity.state='matched';succeeded++;for(const repeat of onFoot.filter(item=>item.repeatOf===activity.id)){repeat.geojson=activity.geojson;repeat.state='repeat';await saveActivity(repeat);}}else{activity.error=data.detail||`HTTP ${response.status}`;activity.state='failed';failed++;}await saveActivity(activity);await new Promise(resolve=>setTimeout(resolve,1100));}renderLedger();render();fileStatus.className=failed?'muted map-status warn':'muted map-status ok';fileStatus.textContent=`${TILES[activeTile].label} batch complete: ${succeeded} representative routes matched, ${failed} not matched. Repeat journeys retain their travel mileage.`;
    }catch(error){status.className='error map-status';status.textContent=`On-foot matching stopped: ${error.name==='AbortError'?'one activity took longer than 60 seconds':error.message||error}`;}finally{updateQueueButton();}}
  function extractActivities(data){const semantic=Array.isArray(data?.semanticSegments)?data.semanticSegments:[],all=[];for(const segment of semantic)for(const item of Array.isArray(segment?.timelinePath)?segment.timelinePath:[]){const point=parsePoint(item?.point),time=Date.parse(item?.time||'');if(point&&Number.isFinite(time))all.push({...point,time});}all.sort((a,b)=>a.time-b.time);const result=[];for(const segment of semantic){const type=String(segment?.activity?.topCandidate?.type||'').toUpperCase();if(type!=='WALKING'&&type!=='RUNNING')continue;const start=Date.parse(segment.startTime||''),end=Date.parse(segment.endTime||'');if(!Number.isFinite(start)||!Number.isFinite(end))continue;const points=dedupe(all.filter(point=>point.time>=start&&point.time<=end).map(({lat,lng})=>({lat,lng})));if(points.length>1){const mode='on_foot',first=points[0],last=points[points.length-1],googleDistanceM=Number(segment?.activity?.distanceMeters);result.push({id:`${mode}:${start}:${end}:${first.lat.toFixed(5)}:${first.lng.toFixed(5)}:${last.lat.toFixed(5)}:${last.lng.toFixed(5)}`,mode,points,start,end,googleDistanceM:Number.isFinite(googleDistanceM)?googleDistanceM:null});}}return result;}
  function footprintSignature(activity){const cells=[];for(const point of activity.points.filter(inBounds)){const lat=Math.round(point.lat*925),lng=Math.round(point.lng*575),cell=`${lat}:${lng}`;if(cells[cells.length-1]!==cell)cells.push(cell);}const forward=cells.join('|'),reverse=[...cells].reverse().join('|');return `${activity.mode}:${forward<reverse?forward:reverse}`;}
  function classifyRouteRepeats(activities){const groups=new Map();for(const activity of activities){delete activity.repeatOf;const signature=footprintSignature(activity);if(!signature.endsWith(':')){if(!groups.has(signature))groups.set(signature,[]);groups.get(signature).push(activity);}}for(const group of groups.values()){for(let index=1;index<group.length;index++){group[index].repeatOf=group[0].id;group[index].state='repeat';if(group[0].geojson)group[index].geojson=group[0].geojson;}}}
  function renderLedger(){const repeats=onFoot.filter(activity=>activity.repeatOf).length,reps=onFoot.length-repeats,travelM=onFoot.reduce((sum,activity)=>sum+(Number(activity.googleDistanceM)||0),0);$('coverageTravelMiles').textContent=(travelM/1609.344).toFixed(2);$('coverageRepresentatives').textContent=reps.toLocaleString();$('coverageRouteRepeats').textContent=repeats.toLocaleString();$('coverageLedgerDetail').textContent=`${repeats.toLocaleString()} repeated route${repeats===1?'':'s'} avoid a new matcher call. Travel mileage includes all ${onFoot.length.toLocaleString()} activities; coverage still counts each physical segment once.`;$('coverageLedger').classList.remove('hidden');}
  function renderInventory(activities){const grouped=new Map();for(const activity of activities){const centre=activity.points.reduce((sum,p)=>({lat:sum.lat+p.lat,lng:sum.lng+p.lng}),{lat:0,lng:0});centre.lat/=activity.points.length;centre.lng/=activity.points.length;const lat=Math.floor(centre.lat*10)/10,lng=Math.floor(centre.lng*10)/10,key=`${lat.toFixed(1)}°N, ${lng.toFixed(1)}°E`;if(!grouped.has(key))grouped.set(key,0);grouped.set(key,grouped.get(key)+1);}const areas=[...grouped.entries()].sort((a,b)=>b[1]-a[1]);$('coverageUsableActivities').textContent=activities.length.toLocaleString();$('coverageAreaCount').textContent=areas.length.toLocaleString();$('coverageGravesendActivities').textContent=activities.filter(a=>a.points.some(inBounds)).length.toLocaleString();$('coverageTileActivityLabel').textContent=`in the current ${TILES[activeTile].label} tile`;const list=$('coverageAreaList');list.innerHTML='';for(const [name,count] of areas.slice(0,8)){const row=document.createElement('div');row.className='coverage-area-row';row.innerHTML=`<span>Approx. ${name}</span><strong>${count} activities</strong>`;list.append(row);}if(areas.length>8){const more=document.createElement('div');more.className='coverage-area-row';more.textContent=`${areas.length-8} further approximate areas`;list.append(more);}$('coverageInventory').classList.remove('hidden');}
  function parsePoint(value){if(!value)return null;if(typeof value==='string'){const n=value.match(/-?\d+(?:\.\d+)?/g);return n?.length>1?{lat:+n[0],lng:+n[1]}:null;}const raw=value.point||value;const lat=Number(raw.latitude??raw.lat??(Number(raw.latitudeE7)/1e7)),lng=Number(raw.longitude??raw.lng??raw.lon??(Number(raw.longitudeE7)/1e7));return Number.isFinite(lat)&&Number.isFinite(lng)?{lat,lng}:null;}
  function dedupe(points){return points.filter((p,i)=>!i||p.lat!==points[i-1].lat||p.lng!==points[i-1].lng);}
  function inBounds(point){const b=bounds();return point.lat>=b.south&&point.lat<=b.north&&point.lng>=b.west&&point.lng<=b.east;}
  function geoSegments(geojson){const out=[];for(const feature of geojson?.features||[]){const g=feature?.geometry,lines=g?.type==='LineString'?[g.coordinates]:g?.type==='MultiLineString'?g.coordinates:[];for(const line of lines)for(let i=1;i<line.length;i++)out.push([line[i-1],line[i]]);}return out;}
  function pointDistance(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,den=dx*dx+dy*dy,t=den?Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/den)):0;return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy);}
  function attribute(geojson,mode,covered){for(const [start,end] of geoSegments(geojson)){const a=project(start),b=project(end),steps=Math.max(1,Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)/7));for(let i=0;i<=steps;i++){const p={x:a.x+(b.x-a.x)*i/steps,y:a.y+(b.y-a.y)*i/steps};let best,dist=RADIUS;for(const candidate of grid.get(key(p.x,p.y))||[]){if(!candidate.modes.has(mode))continue;const d=pointDistance(p,candidate.a,candidate.b);if(d<=dist){best=candidate;dist=d;}}if(best){const id=best.feature.properties.segment_id;if(!covered.has(id))covered.set(id,new Set());covered.get(id).add(mode);}}}}
  function render(){if(!network||!map)return;const covered=new Map();savedDriving.forEach(g=>attribute(g,'driving',covered));onFoot.filter(a=>a.geojson).forEach(a=>attribute(a.geojson,'on_foot',covered));const complete=[],drive=[],foot=[];let unique=0,driven=0,walked=0,shared=0;for(const segment of segments){const modes=covered.get(segment.feature.properties.segment_id);if(!modes?.size)continue;const metres=+segment.feature.properties.length_m;complete.push(segment.feature);unique+=metres;if(modes.has('driving')){drive.push(segment.feature);driven+=metres;}if(modes.has('on_foot')){foot.push(segment.feature);walked+=metres;}if(modes.has('driving')&&modes.has('on_foot'))shared+=metres;}
    stat('coverageNetworkMiles',network.metadata.total_length_m);stat('coverageUniqueMiles',unique);stat('coverageDrivingMiles',driven);stat('coverageFootMiles',walked);stat('coverageSharedMiles',shared);$('coveragePercent').textContent=`${(unique/network.metadata.total_length_m*100).toFixed(2)}%`;
    if(control)control.remove();map.eachLayer(layer=>{if(!(layer instanceof L.TileLayer))map.removeLayer(layer)});const lines=list=>list.map(f=>f.geometry.coordinates.map(([lng,lat])=>[lat,lng]));const base=L.polyline(lines(network.features),{color:'#a4acb8',weight:1,opacity:.35}).addTo(map),combined=L.polyline(lines(complete),{color:'#7b3fc6',weight:5,opacity:.9}).addTo(map),driving=L.polyline(lines(drive),{color:'#111827',weight:4,opacity:.9}),walking=L.polyline(lines(foot),{color:'#2f7df6',weight:4,opacity:.95});control=L.control.layers({}, {'Eligible network':base,'Completed by any mode':combined,'Driven':driving,'On foot':walking}).addTo(map);
    const completed=onFoot.filter(a=>a.geojson).length;status.className='muted map-status';status.textContent=`${savedDriving.length} saved driving matches and ${completed} temporary on-foot matches analysed. ${complete.length.toLocaleString()} canonical segments completed.`;$('coverageProofDetails').textContent=`Version ${network.metadata.version}; ${network.metadata.segment_count.toLocaleString()} direction-independent OpenStreetMap segments in the fixed boundary. Matched geometry is attributed within ${RADIUS} metres. On-foot results are not saved.`;}
  function stat(id,metres){$(id).textContent=(Number(metres||0)/1609.344).toFixed(2);}
})();
